@startuml

interface GeneralDAO{
    long guardarUser(Usuario user)
    long guardarCliente(Cliente cliente)
    long guardarComida(Comida com)
    long guardarBebida(Bebida beb)
    long guardarPostre(Postre pos)
    long guardarMesa(Mesa mesa)
}

class FinalDAO implements GeneralDAO{}

class Cliente {
    - nombre : "
    - apellido : "
    - telefonos : List<">
}

class Mesa {
    - numMesa : int
    - estado : "
    - capacidad : int
}

class Personal {
    - idPersonal : int
    - nombre : "
    - rol : "
}

abstract class Producto {
    - nombre : "
    - precio : float
    - categoria : "
    - stock : boolean
    - descripcion : "
    + calcImp() : double
}

class Bebida extends Producto{
    + calcImp() : double
}

class Comida extends Producto{
    + calcImp() : double
}

class Postre extends Producto{
    + calcImp() : double
}

' ==== RELACIONES ====
FinalDAO ..> Cliente : gestiona
FinalDAO ..> Mesa : administra
FinalDAO ..> Producto : guarda

Cliente "1" -- "*" Mesa : reserva
Personal "1" -- "*" Mesa : atiende
Mesa "*" -- "*" Producto : contiene
@enduml
