@startuml

class Usuario{
    - nombre : String
    - apellido : String
    - email : String
    - username : String
    - password : String
    - cedula : int
    - fechaNacimiento : LocalDate
    - telefono : int
}

interface GeneralDAO{
    long guardarUser(Usuario user)
    long giardarCliente(Cliente cliente)
    long guardarComida(Comida com)
    long guardarBebida(Bebida beb)
    long guardarPostre(Postre pos)
    long guardarMesa(Mesa mesa)
}

class FinalDAO implements GeneralDAO{}

class Cliente {
    - nombre : "
    - apellido : "
    - telefonos : List<">
}

class Mesa {
    - numMesa : int
    - estado : "
    - capacidad : int
}

class Personal {
    - idPersonal : int
    - nombre : "
    - rol : "
}

abstract class Producto {
    - nombre : "
    - precio : float
    - categoria : "
    - stock : boolean
    - descripcion : "
    double calcImp()
}

class Bebida extends Producto{
    double calcImp()
}

class Comida extends Producto{
    double calcImp()
}

class Postre extends Producto{
    double calcImp()
}
@enduml
